# Docker Tor Configuration
SOCKSPort ${TOR_SOCKS_PORT:-9050}
ControlPort ${TOR_CONTROL_PORT:-9051}
CookieAuthentication 0
Log notice stdout
DataDirectory /var/lib/tor
ClientOnly 1
AvoidDiskWrites 0
SafeLogging 1
